# Generated by Django 5.0.7 on 2024-08-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdatetime',
            old_name='start_datetime',
            new_name='thedatetime',
        ),
        migrations.RemoveField(
            model_name='appointmentdatetime',
            name='end_datetime',
        ),
    ]
